### ISSUE TITLE
Error running "node index"

### ISSUE THREAD

**Issue by franktopel** [DMarby/unsplash-downloader#3]
TypeError: Cannot read property 'concurrent_downloads' of undefined
    at Object.<anonymous> (/Users/connexo/Pictures/unsplash-downloader/index.js:39:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by franktopel** [comment]
Fixed - thanks alot!
