### ISSUE TITLE
Downloader Error Doesn't Remember Previous Downloads

### ISSUE THREAD

**Issue by nrutman** [DMarby/unsplash-downloader#6]
I recently pulled in the latest changes from master and I started downloading photos. The problem is that the downloader no longer seems to remember which files are already downloaded (it used to track this in the `photos.json` file).

I deleted all previously downloaded photos (including the `photos.json` file) and started again. It won't get through 755 downloads without error, and it never writes a `photos.json` file. So every time I restart, it tries to get all 755 images again.

Here is the NPM error log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.1
3 info using node@v0.10.36
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart unsplash-downloader@0.0.1
6 info start unsplash-downloader@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info unsplash-downloader@0.0.1 Failed to exec start script
9 verbose stack Error: unsplash-downloader@0.0.1 start: `node index.js`
9 verbose stack Exit status 8
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid unsplash-downloader@0.0.1
11 verbose cwd /Volumes/Media/Projects/Me/Unsplash Downloader
12 error Darwin 14.4.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.10.36
15 error npm  v2.7.1
16 error code ELIFECYCLE
17 error unsplash-downloader@0.0.1 start: `node index.js`
17 error Exit status 8
18 error Failed at the unsplash-downloader@0.0.1 start script 'node index.js'.
18 error This is most likely a problem with the unsplash-downloader package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js
18 error You can get their info via:
18 error     npm owner ls unsplash-downloader
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

And here is my config (which I updated when I pulled):
```
module.exports = exports = {
	concurrent_downloads: 5,
	folder_path: '/Volumes/Media/Pictures/Unsplash',
	git_push: false,
	post_command: false,
	create_zip: false,
	all: false,
	check_for_deleted: true
}
```

Any thoughts as to what's going on? Why won't it track what photos are downloaded already?

Thanks,
-Nate

**Comment by DMarby** [comment]
Hello,

thanks for reporting the issue. 
The project has been broken for a while,
and I've been too busy to look into it, but I'll try to fix it this weekend.

Sincerely,
David
